name: Publish Package
on:
  workflow_dispatch:

  release:
    types: [created]
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    # Setup .npmrc file to publish to npm
    - name: Setup Node JS environment for npm
      uses: actions/setup-node@v6

    - run: npm i
    # Build
    - run: npm run build
    # Publish to npm
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v6
      with:
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@revolist'
    # Publish to GitHub Packages
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
